### ISSUE TITLE
Private functions appear in the intelligent code completion recommended list 

### ISSUE THREAD

**Issue by tzSharing** [vlang/intellij-v#9]
### Describe the bug

Private functions appear in the intelligent code completion recommended list , which should not appear.

### Expected Behavior

Private functions should not be recommended in the list

### Current Behavior

![private](https://github.com/user-attachments/assets/35f10407-9b8f-49ad-9cb3-d09b8b17053f)

### Environment details (`v doctor` output)
Windows 10  64bit
V 0.4.7 8fec4ce

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

```yaml
IntelliJ IDEA 2024.1.4 (Community Edition)
Build #IC-241.18034.62, built on June 21, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Kotlin 插件: K2 Kotlin 模式(Alpha)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.zh (241.271)
  io.vlang (0.0.1-beta.5)
Kotlin: 241.18034.62-IJ
```

### Plugin Version

0.0.1-beta.5
